// 10 MILLION STACK TEST WITH CONDITIONS

SET RG1 0;          // COUNTER
SET RG2 10000000;   // 10 MILLION
SET RG3 0;          // ACCUMULATOR
SET RG4 0;          // TEMP

// LOOP START (STATEMENT 4)
PUSHQ RG1;          // PUSH COUNTER
PUSHQ RG3;          // PUSH ACCUMULATOR

POPQ RG1;           // POP COUNTER
POPQ RG3;           // POP ACCUMULATOR

SET RG4 RG1;        // COPY COUNTER TO RG4
MOD RG4 2;          // RG4 % 2 (CHECK IF EVEN)

CMPE RG4 0;         // IF RG4 == 0 (EVEN)
JUMP 16;            // JUMP TO EVEN PATH

ADD RG3 1;          // ODD: ACCUMULATOR += 1
SKIP;               // SKIP THE EVEN PATH
ADD RG3 2;          // EVEN: ACCUMULATOR += 2

PUSHQ RG3;          // PUSH ACCUMULATOR
POPQ RG3;           // POP ACCUMULATOR

ADD RG1 1;          // INCREMENT COUNTER
CMPL RG1 RG2;       // IF RG1 < RG2
JUMP 4;             // JUMP BACK TO LOOP START

EXIT 0;
END;
