SET RG1 48;         // SET IS JUST LIKE MOV IN ASSEMBLY
PUSH RG1 8;         // PUSH VALUE OF RG1 ONTO THE STACK BY 8 BYTES
POP RG2 8;          // POP 8 BYTES OFF THE STACK INTO RG2


// -- COMPARE --
CMPE RG1 RG2;       // COMPARE IF RG1 == RG2
JUMP 9;             // JUMP TO STATEMENT 11 IF TRUE
SKIP;               // OTHERWISE SKIP
SETMODE PREV VAL;   // AFTER SKIP, WE WANT TO ADD A VALUE TO RG2
ADD RG2 9;          // ADD RG2 BY 9



// [STATEMENT 9 PART]
{

	SKIP;           // THIS IS STATEMENT 9
					// NOTICE HOW {} AS ORGANIZERS WORK TOO?
	SET RLA RDP;    // SET THE LOAD ADDRESS TO THE STATIC DATA POINTER
					// SET RLA RSP IF YOU WANT LOAD FROM THE STACK
	ADD RLA 2;      // NOW WE WANT TO OFFSET THE LOAD ADDRESS BY 2 BYTES
	LOAD RG3 8;     // LOAD STATIC DATA + 2 INTO RG3 BY 8 BYTES

}


EXIT 0;                 // MAKE SURE TO EXIT PROPERLY OTHERWISE THE JRM WILL WARN


// ALWAYS END; BEFORE THE STATIC DATA, OTHERWISE THE COMPILER WILL THROW AN ERROR!
END;


WE'VE REACHED THE STATIC DATA SECTION!\0
LOVE YOU MOM AND DAD!\0
SKIBIDI TOILET SLICERS\0
ESCAPE CODE TEST \n\t\123\9\0
UNLESS YOU ADD '\n' or '\t' INTO THE STATIC DATA,
ANY NEWLINE OR         TAB CHARACTER IS DISCARED\0
