// 1 MILLION STACK PUSH/POP TEST
// NO LABELS - RAW STATEMENT NUMBERS

SET RG1 0;          // COUNTER
//SET RG2 100000000;    // LIMIT
//SET RG2 10000;

// LOOP START (STATEMENT 2)
PUSHQ RG1;         // PUSH COUNTER
ADD RG1 1;          // INCREMENT COUNTER
POPQ RG3;          // POP INTO RG3 (VERIFY)
CMPL RG1 RG2;       // IF RG1 < RG2
JUMP 2;             // JUMP BACK TO STATEMENT 2 (LOOP)

EXIT 0;
END;
