SET RJM 1;         // SET THE JRMCALL TO PRINT MODE
SET RJ1 RDP;       // SET THE 1ST ARGUMENT TO THE STATIC DATA POINTER
SET RJ2 0;         // THE STRING IS NULL TERMINATED, SO THE LENGTH CAN BE 0
JRMCALL;           // JRMCALL IG
EXIT 0;            // EXIT WITH CODE 0
                   // AFTER END, BELOW IS THE STATIC DATA CONTAINING THE HELLO WORLD STRING
END;
HELLO, WORLD!\n\0
