// THIS PROGRAM PRINTS OUT A - z IN THE ASCII TABLE
// FIRST, LETS SAY X = 65, WHICH IS 'A' IN ASCII


PUSHQ 65;        // PUSH 65 ON THE STACK BY 8 BYTES (X = 65)
POPQ RG1;        // LOAD X INTO REGISTER A
PUSHQ RG1;       // NOW OF COURSE POP IS JUST A SHOWCASE, SO ILL JUST REPUSH IT


SET RG9 RSB;     // SET RG9 TO THE BASE OF THE STACK


                 // [STATEMENT 5]
LOADQ RG1 RG9;   // RELOAD RG1 FROM THE BASE OF THE STACK (RG1 = X)
CMPH RG1 122;    // CHECK IF RG1 (X) IS HIGHER THAN 'z' (END OF A - z)
JUMP 13;         // IF IT IS JUMP TO PRINT IT, OTHERWISE CONTINUE

CMPE RG1 91;     // IF RG1 IS '['
ADD RG1 6;       // ADD IT BY 6 TO SKIP SYMBOLS, ELSE SKIP TO THE NEXT INSTRUCTION (PUSHB RG1;)

PUSHB RG1;       // PUSH THE CHARACTER ONTO THE STACK BY 1 BYTE
INC RG1;         // INCREMENT RG1
WRITEQ RG1 RG9;  // WRITE RG1 BACK TO X

JUMP 4;          // JUMP BACK TO STATEMENT 4


                 // [PRINT IT] (STATEMENT 13)
PUSHB 10;        // PUSH '\n' ONTO THE STACK
PUSHB 0;         // NULL TERMINATE IT

SET RG2 RSB;     // SET RG2 TO THE START OF THE STACK
ADD RG2 8;       // WE NEED TO GET THE START OF THE STRING, SO ADD IT BY THE SIZE OF X (8 BYTES)

SET RJM 1;       // SET JRMCALL MODE TO 1 (PRINT)
SET RJ1 RG2;     // SET ARG1 TO RG2 (START OF STRING)
SET RJ2 0;       // SET THE STRING'S LENGTH TO 0, BECAUSE ITS ALREADY NULL TERMINATED
JRMCALL;         // MOM SAYS WE HAVE SYSCALL AT HOME


EXIT 0;          // EXIT CLEANLY


                 // MAKE SURE TO ALWAYS MARK THE END OF CODE, BECAUSE DATA IS BELOW
END;

LOVE YOU MOM AND DAD!\0
