C_FLAGS = -I./JSM
GCC_FLAGS = -g -O0
# -DUNFETTERED
#-Ofast
OUTPUT_FOLDER = NOOUBYS_OUTPUT
ALL_C_FILES = $(shell find JSM -name "*.c")
JSM_SOURCE_FILES = $(filter-out JSM/SOURCE/PROGRAMS/%, $(ALL_C_FILES))


JSMC_PROGRAM_FILE = JSM/SOURCE/PROGRAMS/JSMC_PROGRAM.c
JSMC_PROGRAM_FILE: $(JSMC_PROGRAM_FILE)
	gcc $(GCC_FLAGS) $(JSM_SOURCE_FILES) $(JSMC_PROGRAM_FILE) $(C_FLAGS) -o $(OUTPUT_FOLDER)/JSMC



ARGS = $(filter-out $@,$(MAKECMDGOALS))

RUN:
	clear
	./$(OUTPUT_FOLDER)/$(P) $(ARGS)
