C_FLAGS = -I./JSM
GCC_FLAGS = -g -O0
# -DUNFETTERED
#-Ofast



OUTPUT_FOLDER = NOOUBYS_OUTPUT
ALL_C_FILES = $(shell find JSM -name "*.c")
JSM_SOURCE_FILES = $(filter-out JSM/SOURCE/PROGRAMS/%, $(ALL_C_FILES))



.PHONY: JSMC_PROGRAM_FILE



JSMC_PROGRAM_FILE = JSM/SOURCE/PROGRAMS/JSMC_PROGRAM.c
JRM_PROGRAM_FILE = JSM/SOURCE/PROGRAMS/JRM_PROGRAM.c
JSMC_PROGRAM_FILE: $(JSMC_PROGRAM_FILE)
	gcc $(GCC_FLAGS) $(JSM_SOURCE_FILES) $(JSMC_PROGRAM_FILE) $(C_FLAGS) -o $(OUTPUT_FOLDER)/JSMC
	gcc $(GCC_FLAGS) $(JSM_SOURCE_FILES) $(JRM_PROGRAM_FILE) $(C_FLAGS) -o $(OUTPUT_FOLDER)/JRM



ARGS = $(filter-out $@,$(MAKECMDGOALS))



RUN:
	clear
	./$(OUTPUT_FOLDER)/$(P) $(ARGS)



JSMC:
	@clear
	@./$(OUTPUT_FOLDER)/JSMC $(ARGS)



%.jrp: FORCE
	@:
FORCE:



JRM:
	@clear
	@./$(OUTPUT_FOLDER)/JRM $(ARGS)
