C_FLAGS = -I./JSM
GCC_FLAGS = -g -Ofast
#-Wstrict-aliasing=1 -flto -fstrict-aliasing
#-fno-strict-aliasing
# -DUNFETTERED
#-Ofast



OUTPUT_FOLDER = OUTPUT
ALL_C_FILES = $(shell find JSM -name "*.c")
JSM_SOURCE_FILES = $(filter-out JSM/SOURCE/PROGRAMS/%, $(ALL_C_FILES))
JRM_SOURCE_FILES = JSM/SOURCE/JRM/JRM.c JSM/SOURCE/PROGRAMS/JRM_PROGRAM.c
JSMC_SOURCE_FILES = JSM/SOURCE/JSMC/JSMC.c JSM/SOURCE/PROGRAMS/JSMC_PROGRAM.c



.PHONY: JSMC_PROGRAM_FILE

JSMC_PROGRAM_FILE: $(JSMC_PROGRAM_FILE)
	mkdir -p $(OUTPUT_FOLDER)
	gcc $(GCC_FLAGS) $(JSMC_SOURCE_FILES) $(C_FLAGS) -o $(OUTPUT_FOLDER)/JSMC
	gcc $(GCC_FLAGS) $(JRM_SOURCE_FILES)  $(C_FLAGS) -o $(OUTPUT_FOLDER)/JRM



ARGS = $(filter-out $@,$(MAKECMDGOALS))



RUN:
	clear
	./$(OUTPUT_FOLDER)/$(P) $(ARGS)


%.jsm: FORCE
	@:

%.jrp: FORCE
	@:

FORCE:


JSMC:
	@clear
	@./$(OUTPUT_FOLDER)/JSMC $(ARGS)


LAZYCOMP:
	@clear
	@./$(OUTPUT_FOLDER)/JSMC TEST/$(ARGS).jsm COMPILED_JRPS/$(ARGS).jrp


LAZYRUN:
	@clear
	@./$(OUTPUT_FOLDER)/JRM COMPILED_JRPS/$(ARGS)



JRM:
	@clear
	@./$(OUTPUT_FOLDER)/JRM $(ARGS)



GET_JRM_ASM:
	@clear
	@gcc -S $(GCC_FLAGS) -g0 -fverbose-asm JSM/SOURCE/JRM/JRM.c -o JRM.s
